import Footer from "./Layout components/Footer";
import Header from "./Layout components/header/Header";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "React Challenges",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col justify-center ">
          <Header />
            <main className="flex-1">{children}</main>
          <Footer />
        </div>
        {/* <Header />
        <div className="flex  w-dvw justify-between ">
        {children}
        </div> */}
      </body>
    </html>
  );
}
